### ISSUE TITLE
Edit content on the landing page of IronHacks

### ISSUE THREAD

**Issue by ManthanKeim** [ironhacks/ironhacks-app#102]
**Summary**
1. Add COVID-19 hacks to past hacks.
2. Change Visualisations to ________,

**Description**
Provide a more detailed description here

**Comment by ybvau** [comment]
https://docs.google.com/document/d/19ZNssa5WzZu8Vp21-75XdBIjEJZHGbfskjK9L4bFT58/edit#heading=h.68sh12fpegr <<Document with edits made for landing page.

**Comment by ManthanKeim** [comment]
if you could also get me the image for COVID 19 challenge, it was in a ppt I forgot.

**Comment by ManthanKeim** [comment]
Deployed the changes to dev site.

**Comment by ybvau** [comment]
@ManthanKeim Apologies -- I shared the wrong project information. I updated the doc to accurately reflect it now and iterated the three projects to be displayed on the website as well as updated the term "notebook" to "submission" displayed on the bottom. As well as that, I believe there are additional sponsors.

**Comment by ManthanKeim** [comment]
e4e7221

Done

**Comment by sbrunswi** [comment]
This is great - I think @ybvau dropped the ball! let's move this over!
