### ISSUE TITLE
[FEATURE]  Adding a tab to participants navigation bar

### ISSUE THREAD

**Issue by ManthanKeim** [ironhacks/ironhacks-app#106]
**Summary**
Additional bar with content changes according to the cohort. For example, we should have a page called "examples" that would lead them to either the summaries or the notebooks! 

**Description**
Right now, there isn't any way to show example notebook or description from past hacks to give some idea to participant if they are stuck somewhere, or motivate them to submit. What we'll do is add a tab right after "Tutorials" participants hack dashboard(screenshot attached). We can do this in two ways, one hardcode the submission from the firebase or add a button on the platform to upload notebooks realtime.

**Does this feature solve an existing problem**
Yes, right now we're adding notebooks in task document which is hard to find, adding them to a new tab called "examples" will make it convenient.

**Does this the solution you'd like**
Yes, if dynamic button is added which give us liberty to add or delete notebooks will be good.

**Describe alternatives you've considered**
If not dynamic, we'll hardcode the submission file from the firebase.

**Additional context**
![Screenshot 2021-06-29 at 1 12 02 AM](https://user-images.githubusercontent.com/23071741/123695793-a02e5c00-d878-11eb-9575-fcdbd4dd2349.png)

**Comment by sbrunswi** [comment]
@harshpavuluri  - we need to detail this a little more!

**Comment by ManthanKeim** [comment]
Update as of Sep 11 - Example tab is added in the admin side of the platform but still has to be added in the participant's side. After developing the participant's side, integration of both has to be done.

**Comment by ManthanKeim** [comment]
## Just a sample of how the feature will look(in beta)

<img width="1792" alt="Screenshot 2021-09-20 at 15 31 36" src="https://user-images.githubusercontent.com/23071741/134062946-db0a2a1c-39c8-4734-bfde-9a689b5bf57c.png">
