### ISSUE TITLE
[FEATURE] Add number of submission to the result page

### ISSUE THREAD

**Issue by sbrunswi** [ironhacks/ironhacks-app#108]
**Summary**
Currently, we only show the number of hackers but we are not showing the number of submission for a particular round. This should be added in same name color like the number of hackers (blue). 

**Description**
1. Pull the information about number of submissions from the json file with the results
2. Count submissions that cannot be scored: e.g. someone submitted but gets 0; count as submission: so also count those with a score of 0
3. Should be published for overall hack within the cohort: it is not a cohort specific property but a hack specific one! So the information is the same for both.

![Screen Shot 2021-06-18 at 2 40 51 PM](https://user-images.githubusercontent.com/12464227/122603960-35448000-d043-11eb-9e29-f1ea8dbbaa80.png)
Idea: discuss how we could make this more flexible also for the admin: e.g. you put into the json file; and the result page the admin could delete or not

**Does this feature solve an existing problem**
Yes it does! 

**Does this the solution you'd like**
I want people to see how many people submitted in the challenge; in the ideal world the admin could modify the json via the result page so that he/she can also overwrite it technically 

**Describe alternatives you've considered**
To be discussed! 

**Additional context**

**References**
See screenshot attached 
![Screen Shot 2021-06-18 at 2 40 51 PM](https://user-images.githubusercontent.com/12464227/122604082-5e651080-d043-11eb-918a-6be0975a60c8.png)

**Comment by ManthanKeim** [comment]
20d2ca2308dd3f96fb7ab6411089868378df6def

for now, it's hardcoded... working to make it dynamic

**Comment by sbrunswi** [comment]
@ybvau  and @ERThompson765  - We had a meeting with manthan and we know have the scores up for exploration, and we also display the submission size! So your communication should be on target for this now and point them to the new feature!
