### ISSUE TITLE
[BUG] Peers tab with Cohort specific tab not working now

### ISSUE THREAD

**Issue by harshpavuluri** [ironhacks/ironhacks-app#109]
**Summary**
Peers tab with cohort features on dev site cannot be "demoed" using the opendigital account (researchopendigitalinnovation@gmail.com) account. 

**Description**
When opening the peers tab on the results page, we need to be able to show notebooks or summaries based on which cohort the participant was in.  Currently, it looks like that the admin (opendigital) is not part of any cohort). 

So a solution is to put the opendigital account back into a cohort. 

**Expected behavior**
Supposed to see notebooks or summaries based on which cohort you are in (the open digital account).

**Comment by ManthanKeim** [comment]
![Uploading image.png…]()

Apparently, on dev it works.

**Comment by sbrunswi** [comment]
Manthan. Harsha did not set up the task correctly. It is not a bug but you deleted the demo submissions/ notebooks and so now we don’t see them anymore.

**Comment by ManthanKeim** [comment]
Added the open digital(IronHacks.team@gmail.com) account to cohort coordinated trust.
