### ISSUE TITLE
Stats/Click data pre processing

### ISSUE THREAD

**Issue by ManthanKeim** [ironhacks/ironhacks-app#127]
**Summary**
Preprocess the stats json from firebase and reference them to users for clicker and owner of the clicked data notebook.

**Description**
1. Get the Json from firebase/export json.
2. Convert into CSV for pre processing.
3. Get both userID of clicker and owner
4. Get/Export user json from firebase
5. Reference them.
6. Make a final database.

**Comment by jialincheoh** [comment]
Summary 
Enable sharing of notebooks with others. 

Description
There is a click button somewhere that will enable sharing of notebooks with others.

**Comment by ManthanKeim** [comment]
[finalreord.csv](https://github.com/ironhacks/ironhacks-app/files/9016274/finalreord.csv)

Closing
