### ISSUE TITLE
[BUG] Calender frame issue on Safari on MacOS

### ISSUE THREAD

**Issue by ManthanKeim** [ironhacks/ironhacks-app#132]
**Summary**
Can't view calendar on Safari.

**Description**
[Error] Blocked a frame with origin "https://www.google.com" from accessing a frame with origin "https://dev.ironhacks.com". Protocols, domains, and ports must match.
	Global Code (inject.js:587)

**Steps To Reproduce**
1. Starting here: 
2. Do this action:
3. Then  '....'

**Expected behavior**
What is was supposed to happen instead.

**Screenshots**
![Screen Shot 2022-07-23 at 1 30 18 PM](https://user-images.githubusercontent.com/23071741/180616281-e736d674-330a-4227-80f2-3e4aab6e832b.png)

**Device Info**
- [ ] Desktop
  - [ ] iOS (version: __ )
  - [ ] Windows (version: __ )
  - [ ] Linux (version: __ )

-  [ ] Mobile 
  - [ ] iPhone (model: __ )
  - [ ] Android (model: __ ) 

**Browser** 
  - [ ] Chrome (version: __ )
  - [ ] Other: ____ 

**Supporting Files**
Include links to logfiles, pastebins, GitHub Gists, etc..

**Comment by sbrunswi** [comment]
Is this solved? @ManthanKeim
