### ISSUE TITLE
Reach out to Github for collaboration hack

### ISSUE THREAD

**Issue by ManthanKeim** [ironhacks/ironhacks-app#134]
**Summary**
Use online resources to connect to GitHub/MLH to list IronHacks.

**Description**
https://github.com/github/hackathons
https://guide.mlh.io

**Comment by harshpavuluri** [comment]
Working on a plan for this. Might also be worth exploring making a Devpost hackathon as well. From my experience, this tends to be the go-to for hackathons used for a variety of big university hackathons (Rutgers, Princeton, etc).

**Comment by ManthanKeim** [comment]
We can also reach out to Purdue Student organization specially from computer science and computer engineering department, including the link with the emails: 

https://www.cs.purdue.edu/undergraduate/student_life.html

**Comment by harshpavuluri** [comment]
https://docs.google.com/document/d/1kfZJmii_pDlQlWfZDLx09sMV3ezqRa5YTQT7pxO4em4/edit


I've organized my notes here in the Google drive. We can use that as a live document and update it as we go.
