### ISSUE TITLE
Review Task Statement - DWD

### ISSUE THREAD

**Issue by ManthanKeim** [ironhacks/ironhacks-app#137]
**Summary**
Reviewing the task statement for the upcoming hack . (DWD Data)

**Comment by harshpavuluri** [comment]
- Data updates are going to coming as soon as next week (9/8/2022)

Need to talk about:
- [ ] Recurring weekly updates to data
- [ ] Rough timeline for hack

**Comment by sbrunswi** [comment]
this is completed.
