### ISSUE TITLE
Make changes to blog suggested by Dr. Sun

### ISSUE THREAD

**Issue by ManthanKeim** [ironhacks/ironhacks-app#144]
Blog:

First paragraph - why unemployment is have a issue, what the hack recovery is about, first two paragraphs need to be organized, information is repetitive and not very clear, three weeks, about the challenge, it will run is 4 weeks, how it’s unique, more information about the dataset, first paragraph is about challenge, second paragraph about dataset, general category of predictors, impact of model budding in third paragraphs,

First paragraph - general characteristics of challenge

Second paragraph - dataset

Third paragraph - impact of models, challenge

We don’;t have to say, how many rounds, multiple, submission,

For certificates, show on their CV,  how the challenge is impacting them,

https://badgr.com/auth/login

If you sign-up to our platform, you can follow along about updates and new challenges.: remove this

One sentences : highlight them

Design of blog/website:

Link to previous challenges: make it hyperlink

**Comment by sbrunswi** [comment]
@ManthanKeim  - this is not in a project!
