### ISSUE TITLE
[BUG] Notebook viewer not working

### ISSUE THREAD

**Issue by sbrunswi** [ironhacks/ironhacks-app#145]
**Summary**
When I use the dev platform or the live platform and try to open a notebook via our internal notebook viewer, the notebook is not loading! So that 

**Description**

**Steps To Reproduce**
1. Starting here: Log-in to dev and live (www.ironhacks.com)
2. Do this action: Go to the tutorials and load an example notebook
3. Then  I get an error message saying that notebook cannot be viewed. 

**Expected behavior**
I should be able to see the notebook 

**Screenshots**

**Device Info**
- [x] Desktop
  - [x] iOS 
  - [ ] Windows (version: __ )
  - [ ] Linux (version: __ )

**Browser** 
  - [x] Chrome 
  - [x] Other: Safari 

**Supporting Files**

**Comment by ManthanKeim** [comment]
All the notebook are fetched from GitHub using it's raw link, so one should be cautious of moving a notebook into archived folder or just change it's title, as it's change the ID linked with the IronHacks platform. I see @harshpavuluri moved the tutorials into the archived folder so they are not found on the platform.

**Comment by harshpavuluri** [comment]
Yup. I've been moving things around for the tutorials at least so the template was in there. Just need the new link is all

**Comment by ManthanKeim** [comment]
It's all good, it's not your fault, just how the notebook viewer works.

**Comment by ManthanKeim** [comment]
So I took them out of archive for now @harshpavuluri , because I'm not sure where else we use these links for tutorials, so can't change the schema for now. @sbrunswi all the notebook works as usual now.

**Comment by sbrunswi** [comment]
Yes. Important to keep in mind to update links. I can’t always track and
monitor you. Be aware.

**Comment by sbrunswi** [comment]
I think we should go through all pages and check links and reembedd. I always did this in the past. We should archive and reembed.
