### ISSUE TITLE
[BUG] U don't see the survey once u click on get the task 

### ISSUE THREAD

**Issue by jialincheoh** [ironhacks/ironhacks-app#146]
**Summary**
You don't see anything once u attempt to click on the "view live document" on the task

**Expected Behavior**
You should be able to see the pre-survey [https://purdue.ca1.qualtrics.com/jfe/form/SV_0HP8cZFaY7JfKgC](https://purdue.ca1.qualtrics.com/jfe/form/SV_0HP8cZFaY7JfKgC )  once you "get the task" on the platform.

**Comment by sbrunswi** [comment]
@ManthanKeim  - is this solved?

**Comment by ManthanKeim** [comment]
@jialincheoh i think you did not enable the survey earlier, that's why, I solved this, let me know if you still cannot. We can close this issue.
