### ISSUE TITLE
[Development] Mailchimp Add Cloud Function

### ISSUE THREAD

**Issue by harshpavuluri** [ironhacks/ironhacks-app#148]
Summary: 
For the development and discussion of the cloud function that will automatically add users to the email list in our Mailchimp once they register for a hack

- [ ] Study the Mailchimp API
- [ ] Start building an initial function that will add users to our Mailchimp
- [ ] Test with dummy accounts

**Comment by harshpavuluri** [comment]
`
import mailchimp_marketing as MailchimpMarketing
from mailchimp_marketing.api_client import ApiClientError

try:
  client = MailchimpMarketing.Client()
  client.set_config({
    "api_key": "YOUR_API_KEY",
    "server": "YOUR_SERVER_PREFIX"
  })

  response = client.lists.add_list_member("list_id", {"email_address": "Addie71@hotmail.com", "status": "unsubscribed"})
  print(response)
except ApiClientError as error:
  print("Error: {}".format(error.text))
`
https://mailchimp.com/developer/marketing/api/list-members/add-member-to-list/

Digging through the Mailchimp API, I found this function. We should be able to grab the information needed for this and add users

**Comment by harshpavuluri** [comment]
@ManthanKeim Going to definitely need some help on this because I'm afraid of breaking the app. But I found something that could be helpful.

https://extensions.dev/extensions/mailchimp/mailchimp-firebase-sync

Mailchimp does have a extension for Firebase, so in theory we could use that, but I think we need to add information to the Firestore to allow that to happen.

**Comment by ManthanKeim** [comment]
<img width="1325" alt="Screenshot 2022-10-28 at 5 29 15 AM" src="https://user-images.githubusercontent.com/23071741/198554574-c9e95f17-4f4d-4ed6-a57f-89b8559e1ae6.png">

Done, we automatically get the registered in the mail chimp database as soon as they register on the ironhacks platform, regardless of the hack.
