### ISSUE TITLE
[BUG] Example Page

### ISSUE THREAD

**Issue by jialincheoh** [ironhacks/ironhacks-app#149]
Describe the bug
@ManthanKeim , do u have any issue on the examples page. I couldn't find them.

The examples page doesn't render for the users. When I go to the user front end, I see a blank page.

@sbrunswi, could u elaborate here on the HCI issue that you are talking about yesterday as well?

**Comment by ManthanKeim** [comment]
<img width="1792" alt="Screenshot 2022-10-28 at 5 09 53 AM" src="https://user-images.githubusercontent.com/23071741/198550356-bfbf96f2-0d5a-4458-b3f5-a29484e6ae92.png">

The examples should be viewed as a markdown.

**Comment by ManthanKeim** [comment]
<img width="1792" alt="Screenshot 2022-10-28 at 5 53 07 AM" src="https://user-images.githubusercontent.com/23071741/198561016-6ed709b2-631c-445b-8d1f-b23d7ab9f19e.png">
