### ISSUE TITLE
[FEATURE] Example page requires participants to see both examples and notebooks or just one

### ISSUE THREAD

**Issue by sbrunswi** [ironhacks/ironhacks-app#150]
**Summary**
The example page currently does not show the notebooks. Also, they should not contain first person but should be written in third person as they are more general like a tutorial. 

**Description**
I suggest that we add a link to the notebooks as well. Also, we need to rewrite the examples so that they use third person. This is particularly important for the procedural part. 

In addition, we should have a statement at the top of the example page saying: 

`Below, you find a few examples of data science models that might be of relevance for your challenge.  They should give you some inspiration of what you can try to use during the data science challenge`

**Does this feature solve an existing problem**
Yes: it solves the problem that the examples are currently not written in correct way. 
![Screen Shot 2022-10-31 at 10 13 44 AM](https://user-images.githubusercontent.com/12464227/199031555-e06bf1bf-14d4-4218-b5d5-a8edd7bc8b08.png)

**Comment by crystalhappycat** [comment]
Summary examples are updated.

**Comment by ManthanKeim** [comment]
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/23071741/199131511-3b1c51de-1efd-4487-8baf-aea127e7d366.png">

**Comment by sbrunswi** [comment]
Man than: this does not look good. Font size is off, and it is too squeezed. Put it into pink like in the markdown editor and same style. Also more space. 

Please see my issue on show cases and user analytics. Urgent.

**Comment by ManthanKeim** [comment]
<img width="1792" alt="Screenshot 2022-11-01 at 9 32 38 AM" src="https://user-images.githubusercontent.com/23071741/199245498-66934237-af2e-4c71-b512-f69918b91d9f.png">

Is this good @sbrunswi ?

**Comment by sbrunswi** [comment]
Too big in font size! Also remove `summary of` below. 

@aronlindberg  and @crystalhappycat: Please also review. 
Also, we need to decide when to post this.

**Comment by ManthanKeim** [comment]
"Summary of" is the title which can be changed from the admin portal only, I just did one.
