### ISSUE TITLE
[Examples] Implement Examples as Treatment on Nov 2nd midnight

### ISSUE THREAD

**Issue by jialincheoh** [ironhacks/ironhacks-app#151]
- Nov 2nd, 2022 at midnight, examples will be shown to participants. 

- summary + notebooks VS notebooks only ( examples follow treatment condition )

- Examples don't get removed and will remain throughout the hack to avoid confusion.

**Comment by ManthanKeim** [comment]
![Screenshot 2022-11-02 at 1 29 54 PM](https://user-images.githubusercontent.com/23071741/199560244-511867b2-f93c-4f7c-97da-3d042a4f7756.png)

**Comment by ManthanKeim** [comment]
![Screenshot 2022-11-02 at 3 20 40 PM](https://user-images.githubusercontent.com/23071741/199581935-e8bf23bf-ee38-4a5a-90ae-4ca5426d9d6c.png)

![Screenshot 2022-11-02 at 3 20 50 PM](https://user-images.githubusercontent.com/23071741/199581958-991beaee-ece9-4281-a372-e1bec3917cb9.png)
