### ISSUE TITLE
Restrict registration to gmail accounts

### ISSUE THREAD

**Issue by sbrunswi** [ironhacks/ironhacks-app#25]
**Summary**
In order to access the bigquery database with a key users need a gmail account. Thus, I suggest that we consider gmail registrations only. Safegraph does the same. Alternatively we could keep it as it is and simply remove all non gmail accounts when assigning them to the groups of the hack. We need to discuss this!

**Description**
 - Keys in bigquery can only be generated for users with a gmail account or one associated with a gsuite. Unless we move away from using bigquery, I do not see another solution then limiting access to people that fulfil those requirements. At the same time it is nice to have people explore our hack selection page without a gmail account so we can also think of a way where we mention it in the internal landing page that those who have signed up with a non-gmail account, are unable to participate in the hack? Let's discuss.

**Comment by charrismatic** [comment]
Updated on hub.ironhub.com now
