### ISSUE TITLE
integrate google analytics with platform to track user-level data

### ISSUE THREAD

**Issue by sbrunswi** [ironhacks/ironhacks-app#33]
**Summary**
It is essential that we can trace back the events and actions on the platform to a user! This is also describe in our dropbox paper [document] (https://paper.dropbox.com/doc/Behavioral-trace-data--A48C92goZFWj_TArUepFju0JAg-u6oYgXQtKvsVBa88TGTcI). It is needed that we set-up the user-ID in the app, and also then add additional events as they are needed. 

**Description**
Currently, we only have device-level trace data. We need user-ID level trace data. After reading up on it, I wonder if there is something missing on our website in the code! I think gtag.js might solve the problem? You are the Javascript developer so I do not know but it could be an option! Please address this. 

https://support.google.com/analytics/answer/3123666?hl=en
https://developers.google.com/analytics/devguides/collection/gtagjs/cookies-user-id
https://support.google.com/analytics/answer/3123666?hl=en

**Does this feature solve an existing problem**
Without having user tracking we cannot run the experiment! We need this for scoring also so please address this! 

**Does this the solution you'd like**
What we need: 
1) user-Id level tracking: 
```
[userID,timestamp,event, timestamp, event, ...]
```
2) Definition of page specific events
 - Hack-select page
 - registration page
 - tutorial page
 - task page
 - workspace/hub
 - dashboard

3) Storage of data in BigQuery? or elsewhere! 

**Describe alternatives you've considered**
Alternative solutions _ I assume writing the event handling ourselves! As it was done in the past! Or an alternative service? 

**Additional context**

**References**
https://support.google.com/analytics/answer/3123666?hl=en
https://developers.google.com/analytics/devguides/collection/gtagjs/cookies-user-id
https://support.google.com/analytics/answer/3123666?hl=en

**Comment by charrismatic** [comment]
Feature implemented with User Metrics function
https://github.com/ironhacks/ironhacks-app/blob/development/src/util/user-metrics.js
