### ISSUE TITLE
Python package google.cloud cannot be imported even though installed in hub container

### ISSUE THREAD

**Issue by sbrunswi** [ironhacks/ironhacks-app#34]
**Summary**
Google.cloud package does not import even though pre-installed. 

**Description**
I running both python and R notebooks in the hub. I have created my own notebooks in Python and R. Today, i tried to import google.cloud as it is shows up as a pre-installed package but it did not work. I also tried to install it again with pip install but no luck. I am not sure what is going. For Jia it works. 

**Steps To Reproduce**
1. Starting here: Go to workspace, and launch hub. 
2. Do this action:
3. Then  launch a python 3 notebook or a notebook and do this
```
import google.cloud

```
or this

```
#!python3 -m pip install google.cloud
import google.cloud
```
I get an error message: 

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-60680cfa05ad> in <module>
----> 1 import google.cloud

ModuleNotFoundError: No module named 'google.cloud'
```

**Expected behavior**
Well it should just work. 

**Screenshots**

**Device Info**
- [x] Desktop
  - [x] iOS 

-  [ ] Mobile 
  - [ ] iPhone (model: __ )
  - [ ] Android (model: __ ) 

**Browser** 
  - [ ] Chrome (version: __ )
  - [ ] Other: ____ 

**Supporting Files**
[without installing](https://www.dropbox.com/s/qarxv6u9m4pcosk/Screenshot%202020-08-04%2019.49.26.png?dl=0)
[with installing it](https://www.dropbox.com/s/kt64yff4om03qf1/Screenshot%202020-08-04%2011.00.08.png?dl=0)
[list of libraries installed](https://www.dropbox.com/s/mquco2iubykrgy2/Screenshot%202020-08-04%2011.22.20.png?dl=0)

**Comment by charrismatic** [comment]
The line 

```
#!python3 -m pip install google.cloud
```
is commented out and will not run. 

Trying to run this directly in the hub `python3 -m pip install google.cloud` works as expected. New hub containers should already have this package installed though.
