### ISSUE TITLE
DEV SITE needed

### ISSUE THREAD

**Issue by sbrunswi** [ironhacks/ironhacks-app#35]
**Summary**
Matt, in order to test and demo the hack it would like to suggest a dev site. I cannot get donors to fund it if we do not show the complete workflow so if we have the submission page also ready we can show that as well even prior to the submission is opening. Also, it would help us with testing. Please let me know what is holding you up.

**Description**
NA

**Comment by charrismatic** [comment]
Most of the setup for this is done on the firebase side. The configuration is added as of de5edd48b4d15d21a0235167a2b4d2d31aa98301 

Notes: The development site is now decoupled from the live sites database so things like user authentication, userId, and hackId will no longer be the same across sites, As well as form handling will need to be handled by separate set of forms in testing to make sure they are sent to the correct endpoint.

dev.ironhacks.com
