### ISSUE TITLE
Installation of extension for word wrapping and removal of other extensions

### ISSUE THREAD

**Issue by sbrunswi** [ironhacks/ironhacks-app#36]
**Summary**
This extension needs to be installed in all containers prior to the start of the competition

**Description**
1. Add 
https://github.com/jupyterlab/jupyterlab/issues/6374
2. then block the use of additional extensions

**Comment by charrismatic** [comment]
The link jupyterlab/jupyterlab#6374 is not an extension.

> That menu item only works for text files, not for notebook cells (any notebook cell type). In fact, you'll notice that word wrap is automatically enabled for markdown and raw cells (in 1.0a3), and disabled for code cells. You can change that in the Advanced Settings for the notebook.

ref: https://github.com/jupyterlab/jupyterlab/issues/6374#issuecomment-494245575

The setting is enabled under settings/notebook 

```
{
    "codeCellConfig": {
        "lineWrap": "on",
    }
}
```

If an extension is required please provide the link to the package so it can be installed

**Comment by sbrunswi** [comment]
Yes I agree. You are right. I found an extension: 
[Code wrapper](https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/codefolding/readme.html)

I have not tried myself; However, we could also make this a nice forum post to post some technical issue? Thoughts?

**Comment by charrismatic** [comment]
Hub is updated. Word wrapping is available in settings and extensions are disabled now
