### ISSUE TITLE
Email template for email notification forum

### ISSUE THREAD

**Issue by sbrunswi** [ironhacks/ironhacks-app#37]
**Summary**
Template for email notifications

**Description**

Subject: New forum post on IronHacks.com

Hi IronHacker, 
There is a new forum post with the **title** [title] available in the forum of the [Data Science Challenge Summer 2020]. 
Check it out [here](link). 

The IronHacks team

**Comment by charrismatic** [comment]
This is now working ref: https://github.com/ironhacks/ironhacks-cloud-api/commit/e65b34a02358e2e916e38e2d98b60ecd33e5ce99
