### ISSUE TITLE
Removing users from a hack

### ISSUE THREAD

**Issue by sbrunswi** [ironhacks/ironhacks-app#38]
**Summary**
Currently, we cannot remove registered users from a hack! There is a need to be able to remove users from the hack (but not from the platform). 

**Description**
After we open registration, there is a hack user list. We need to be able to modify that. One essential function we need is a remove user function.

There should be a front-end features for removing users 
- basic feature: Tick-box; removing users by clicking an "unregister" button
- better feature: having a list of users for upload that should be "removed" (e.g. comma separated list .csv or .txt file)
- Even more: having a feature that allows us to add users (not sure if we can do that but it would something good to have) 

**Does this feature solve an existing problem**
Yes, it would solve the problem of having users in a sample that should not be there! 

**Does this the solution you'd like**
Yes! 

**Describe alternatives you've considered**
Not really - just going to firebase and removing it there :-) I doubt that this is a good solution. 

**Additional context**

**References**

**Comment by charrismatic** [comment]
This feature is now available via f108565d35f511a17932bbe21891748997d573f2
