### ISSUE TITLE
[BUG] Error 403 Access Forbidden when trying to make a query

### ISSUE THREAD

**Issue by RCODI** [ironhacks/ironhacks-app#40]
**Summary**
When making a request to BigQuery after following all of the instructions [in the Python tutorial](https://ironhacks.com/notebook-viewer?path=https://raw.githubusercontent.com/ironhacks/Tutorials-COVID-19/master/part-2/Part-II-BigQuery-and-notebook-Python.ipynb), I run into an "Access Forbidden" error.

**Description**
The code ran in my Jupyter notebook:

```
!python3 -m pip install google.cloud
!python3 -m pip install pandas
!python3 -m pip install numpy

import os
import pandas
from google.cloud import bigquery
from google.oauth2 import service_account
from google.cloud.bigquery import magics

os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = '/home/jovyan/service-account.json'
bigquery_client = bigquery.Client(project='ironhacks-covid19-data')
bigquery_client = bigquery.Client()

QUERY = """

SELECT *
FROM ironhacks-covid19-data.ironhacks_covid19_training.covid19_tests_cases_deaths_IN

"""

query_job = bigquery_client.query(QUERY)
data = query_job.to_dataframe()
data.head()
```

**Steps To Reproduce**
1. Get Shatayu Kulkarni's key from Firebase
2. Run the above code

**Expected behavior**
The below error:

`403 POST https://bigquery.googleapis.com/bigquery/v2/projects/ironhacks-covid19-data/jobs: Access Denied: Project ironhacks-covid19-data: User does not have bigquery.jobs.create permission in project ironhacks-covid19-data.`

**Screenshots**
n/a

**Device Info**
- [x] Desktop
  - [ ] iOS (version: __ )
  - [ ] Windows (version: __ )
  - [ ] Linux (version: __ )

-  [ ] Mobile 
  - [ ] iPhone (model: __ )
  - [ ] Android (model: __ ) 

**Browser** 
  - [ ] Chrome (version: __ )
  - [] Other: Edge (84.0.522.63, Chromium build) 

**Supporting Files**
[Full error log](https://pastebin.com/xCvZ3d7q).
My key is also enclosed. I changed the file type from `.json` to `.txt` to attach it with this issue. Change it back to `.json` before uploading.
[service-account.txt](https://github.com/ironhacks/ironhacks-app/files/5126848/service-account.txt)

**Comment by jialincheoh** [comment]
Issue addressed
