### ISSUE TITLE
[BUG] Permission bug -  users who are not registered can see results

### ISSUE THREAD

**Issue by sbrunswi** [ironhacks/ironhacks-app#41]
**Summary**
When a users without registration clicks on `Results` they can see/access to scores. They should not have permission rights to do so! 

**Description**
When a users without registration clicks on `Results` they can see/access to scores. They should not have permission rights to do so. This has to be adjusted. 

**Steps To Reproduce**
1. unregistered users goes to "results"
2. clicks on it "results" tab
3. see's the [table] (https://www.dropbox.com/s/5a1cllbw0stjuf8/Screen%20Shot%202020-09-07%20at%208.58.04%20PM.png?dl=0)

**Expected behavior**
the user should not see the results! only registered users should see the results 

**Screenshots**
see above 

**Device Info**
NA

NA
**Browser** 
NA
**Supporting Files**
Include links to logfiles, pastebins, GitHub Gists, etc..

**Comment by charrismatic** [comment]
This is fixed with 8212894f8692dcf902f62d7d44aa0bb698a091fe
