### ISSUE TITLE
Update of external landing page

### ISSUE THREAD

**Issue by sbrunswi** [ironhacks/ironhacks-app#45]
**Summary**
See this issue: https://github.com/ironhacks/ironhacks-org/issues/14

**Description**
1. Update google docs with respect to 1) dates and 2) context (Protect purdue) and timeline
2. add new logo - see logo Protect Purdue on the last page of [this] ( https://docs.google.com/presentation/d/1fWwxTZJoG2JNYoJd-onKqKKEdJvDvAsAj_0FbRyYFF0/edit?usp=sharing)

**Comment by charrismatic** [comment]
The partner logos slide used on the page is here 
https://docs.google.com/presentation/d/1UaNV67dE0CUaT__tbhl5vRxttwlt9C9mbFYDI02uilI/edit?usp=sharing

**Comment by sbrunswi** [comment]
@charrismatic  https://docs.google.com/document/d/1mrmeTny72b1lLoYxR-1zMuoIavVPPTET6y7NMrYHcFo/edit 
this is the doc we are working from.

**Comment by sbrunswi** [comment]
@ERThompson765 I made additional comments and edits - please review them! @charrismatic when I wrote it the question of R and Python came up again! We can run a hack for both Python and R

**Comment by sbrunswi** [comment]
@charrismatic we discussed a few more changes to this page! One relates to the image at the top! Can you please share the slides that you used to update?

**Comment by sbrunswi** [comment]
I found it it - it is also in here: https://docs.google.com/presentation/d/1UaNV67dE0CUaT__tbhl5vRxttwlt9C9mbFYDI02uilI/edit#slide=id.p

**Comment by sbrunswi** [comment]
https://docs.google.com/presentation/d/1UaNV67dE0CUaT__tbhl5vRxttwlt9C9mbFYDI02uilI/edit#slide=id.p
