### ISSUE TITLE
Skill-data collection at sign-up/adding skill info to profile

### ISSUE THREAD

**Issue by sbrunswi** [ironhacks/ironhacks-app#53]
The issue: Currently we do not have enough information about our population. So it is important that when people sign-up, we ask the skill questions. Ideally we use this to also fill in their profile 

Solution? 
@charismatic: What is an easy fix for this?

**Comment by charrismatic** [comment]
One thing we can do is forward new users to the profile update screen immediately after signing up.

**Comment by sbrunswi** [comment]
@charrismatic I cannot test this! 

Thus, it is not clear yet whether the programming questions are mandatory! This is pivotal for sampling. If not, we have to add a question in the registration survey about that. It is not the best option though unless we manually add those questions to the profile! Please keep the sampling issue in mind! 


@ERThompson765  please coordinate with Matt so that we have our registration survey ready by tomorrow! We will be using the question that we are asking in the pre-survey last time and move it to the registration survey unless Matt has made the skill question mandatory!

**Comment by charrismatic** [comment]
I had posted a response and some follow up questions about this that are posted in this thread here. I need some clarification on those before I can complete this task

https://teams.microsoft.com/l/message/19:02353e785cc648fbbc8c641d681e9650@thread.tacv2/1605284462097?groupId=2c60695b-1ffd-4ef9-ba6f-d00ad6a73cf8

**Comment by sbrunswi** [comment]
@charrismatic  thanks for following up (you should have brought this up earlier if you hadnt gotten an answer) - If they just touch the forum once that does not help with the sampling issue - we will not know what skills they have. 

So here is a question: We make them touch the profile at least once - and then? We collect the skill question in the registration form and populate the profile with it (if skill are empty?) 

just to clarify: We need to know there skills to do a mean-difference analysis already after registration and see how much variability we have! 

So here is what I Suggest as two options: 
1) Touch one time as suggested via teams
2) Add skill question to registration survey
3) find a way to use the survey responses to populate the profile  (if possible - otherwise deferred to new issue) 
4) analyze the skill question via qualtrics two days after the registreation starts and then regularly to see what skills our participants have! It is important for us in the communication with them. 

We should also create a new issue for post hack discussion: We should add their final results in a hack into their profile at some point so that they can see how they did over time! but that is for AFTER this experiment.

**Comment by charrismatic** [comment]
I think we've decided to use the registration survey for this until there's a better way handle form validation on the profile.
