### ISSUE TITLE
Calendar functionality not working?

### ISSUE THREAD

**Issue by sbrunswi** [ironhacks/ironhacks-app#55]
**Summary**
When I tried to add the src for the calendar the calendar turned out to render incorrectly

**See screenshot**

Needs to be fixed
![Screen Shot 2020-11-13 at 11 58 43 AM](https://user-images.githubusercontent.com/12464227/99099074-e368e280-25a7-11eb-9b4d-c105a5736364.png)

**Comment by charrismatic** [comment]
It looks like you entered "src="https..." instead of the URL of the calendar.

I'll go ahead and fix it in the admin area.

**Comment by sbrunswi** [comment]
Yeah - but it says calendar src! I did not remember that it is now url so please change label.

**Comment by charrismatic** [comment]
This may lead to some confusion about what you are supposed to enter into the field. Google calendar has a public viewable url which is not valid for the iframe.

The html `src` attribute already represents a valid url but should not be confused with the public url of the calendar. It is meant to be taken from the `src` property of the embed code.

Here we specifically need the calendar embed `src` property to be copied over and inserted into the iframe loaded by the app

![Screenshot from 2020-11-13 12-54-21b](https://user-images.githubusercontent.com/7072452/99105521-ab19d200-25b0-11eb-9379-523a283a8ce4.png)

![Screenshot from 2020-11-13 12-51-45](https://user-images.githubusercontent.com/7072452/99105541-b40aa380-25b0-11eb-9324-2a567a3d6751.png)

![Screenshot from 2020-11-13 13-04-29](https://user-images.githubusercontent.com/7072452/99105644-e3211500-25b0-11eb-9744-3ace16af7341.png)

https://www.w3schools.com/tags/att_src.asp

**Comment by charrismatic** [comment]
There may be a way to build our own calendar customizer tool that builds the url similar to the google customize tool in which case we would only need the calendar id, but that have a risk of google changing their url structure over time and breaking any tool we make to match their url convention

**Comment by sbrunswi** [comment]
ok - I had forgotten it. we need to work on a documentation/manual for the hack. we had this in the past - including non -technical guidelines but maybe we can just copy your instruction somewhere for the documentation.

**Comment by charrismatic** [comment]
There is room on the page for some more detailed instructions. This would probably be the best place so the information is present while you are looking at the form.

**Comment by sbrunswi** [comment]
Good point! just a link to a markdown?
