### ISSUE TITLE
Hack info-banner feature inside challenge

### ISSUE THREAD

**Issue by charrismatic** [ironhacks/ironhacks-app#56]
We would like to have the ability to make event wide announcements displayed at the top of an event area. 

The inspiration for this feature comes from Gitlab's Broadcast Messages / Banner system.

Key properties: 

- message content should be short and fit on a single line 
- be written in plain text or in markdown
- displayed as html
- required start and end date

An optional field for customization could be included to change the background color property

At most a single message can be displayed at any given time.

You should be able to edit the content of the message and update the display times after they are published.

<img width="695" alt="broadcast_messages_banner_v12_10" src="https://user-images.githubusercontent.com/7072452/99108573-8d02a080-25b5-11eb-96e8-337fda39f4f2.png">

https://docs.gitlab.com/ee/user/admin_area/broadcast_messages.html

**Comment by charrismatic** [comment]
I'm not sure what to name this feature yet, we have already been using the term "announcements" internally to refer to the general forum area.

On Gitlab this feature is called "banners" 

https://0xacab.org/help/user/admin_area/broadcast_messages.md

And Bootstrap has a similar component called "alerts" which we will probably use for some part of the design implementation.

https://getbootstrap.com/docs/4.0/components/alerts/

@sbrunswi between `announcements`, `banners`,  `alerts`, and `messages` which one sounds best?

I think that `banners` or `announcements` is most appropriate but it also depends on how you will use them.

**Comment by sbrunswi** [comment]
I agree! I thought that the banner is something that is really visible right after log-in! The forum/board/ is not for that. I think we should discuss the forum/board more. We had discussed the cohort specific forum with actual true interaction and participants and make a post etc. versus the general one. This relates to a different issue though so lets focus on banner versus announcement :) I do not yet understand the major difference between them! ..

**Comment by charrismatic** [comment]
Back when we first discussed this feature I imagined something like Gitlab banner system. The announcement displays in a small one line banner across the top of every page, or in our case the event. They act as announcement/notification alerts site wide (or event wide) so messages can be seen as soon as you login or anywhere within the event space. 

![Screenshot from 2020-11-13 14-42-33](https://user-images.githubusercontent.com/7072452/99114498-e4f1d500-25be-11eb-893a-f2747212dd2b.png)

The solution bridges the gap between and the current use forum posts that require users to actively visit and watch for updates, and a fully integrated user notification system. 

It would allow you to display some brief notification during a period of time at the top of the site.

https://docs.gitlab.com/ee/user/admin_area/broadcast_messages.html

**Comment by sbrunswi** [comment]
Yes I think that is great and aligned with my thinking! Can we automatically populate it with upcoming deadline reminders? If not we have to just do it manually.

**Comment by sbrunswi** [comment]
Info-banner!

**Comment by charrismatic** [comment]
Here is a live view of what this looks on GitLab. We will use this as a model for the design tool in the admin area.

![Gitlab Banner](https://about.gitlab.com/images/8_5/broadcast_md.gif)

[Markdown in Broadcast messages](https://about.gitlab.com/releases/2016/02/22/gitlab-8-5-released#markdown-in-broadcast-messages)

There is a list of properties a banner has [for reference](https://docs.gitlab.com/ee/api/broadcast_messages.html)
