### ISSUE TITLE
Update external page a second time

### ISSUE THREAD

**Issue by sbrunswi** [ironhacks/ironhacks-app#57]
1) Add comments from marketing into the google docs
2) Add sign-up button at the bottom
3) Add testimonial statements and headshot of the winners!

**Comment by charrismatic** [comment]
Adding the text from marketing:

- Rephrase the text in the oval to this:

  > Your Fall 2020 Data Science Challenge: Protect Purdue
You can monitor and predict social distancing behavior at Purdue and our surrounding regions. 

- Change "Sign up here now" to "Register Now" and relocate it to the upper right portion of the screen.

  _\*This is where we decided to add this signup section at the bottom_

- Simplify the text in the headline text to:

  > IronHacks 2020:
A Series of Global COVID-19 Data Science Challenges
Hack for innovation to solve global challenges.

  _\*This text is not different from the existing page text.

For the third part, where do I find the testimonials and headshot images to add.

**Comment by sbrunswi** [comment]
@charrismatic  here are suggested changes :-) testimonials I have added there for you but we have them also on our drive.

https://docs.google.com/document/d/1mrmeTny72b1lLoYxR-1zMuoIavVPPTET6y7NMrYHcFo/edit#

Headshots are here: :-) 

https://app.box.com/s/htg295yusqfmji2doelet8mkv1dlu73z

About here comment:

> IronHacks 2020:
A Series of Global COVID-19 Data Science Challenges
Hack for innovation to solve global challenges.

I suggested to just say


> IronHacks 2020:
A Series of Global COVID-19 Data Science Challenges to Protect Our Communities

She also said we should brand it: COVID-19 Data Science Challenge: Protect Purdue (in the bubble)

**Comment by sbrunswi** [comment]
I think she asked us to simplify the text in the headline text to:

> IronHacks 2020:
A Series of Global COVID-19 Data Science Challenges
Hack for innovation to solve global challenges.

We could just say this: 

> IronHacks 2020:
A Series of Global COVID-19 Data Science Challenges

Testimonials

**Comment by sbrunswi** [comment]
1) Careful read of external page and make sure to cross out text (Rather than deleting), and color coding all changes made in yellow.  https://docs.google.com/document/d/1mrmeTny72b1lLoYxR-1zMuoIavVPPTET6y7NMrYHcFo/edit#
2) Add sign-up bottom at the end
3) Twitter feed at the end 
4) Make head shot bigger!

**Comment by charrismatic** [comment]
this is done please wait before reopening issues
