### ISSUE TITLE
Bug: Subject line after registration to challenge

### ISSUE THREAD

**Issue by sbrunswi** [ironhacks/ironhacks-app#66]
**There is an issue with the subject line after registration**

1. I signed up to the R challenge.
2. I received an email with the Subject line: New Forum Posts. The content stated: 

> Subject line: New forum post on IronHacks.com

> Sabine,
> Your registration confirmation for COVID-19 Data Science Challenge Fall 2020 to Protect Purdue R is confirmed.
> Visit IronHacks.com for news and updates here.
> -IronHacks team

> View the post.

-The IronHacks team

**Solution**
Check Mailchimp integration! Something is off here.

**Comment by charrismatic** [comment]
Fixed with ironhacks/ironhacks-cloud-api@66162ff71613064cf235f8ce5fae07f3cc72f2d6
