### ISSUE TITLE
[FEATURE] Hack Notes - Admin team notes features

### ISSUE THREAD

**Issue by charrismatic** [ironhacks/ironhacks-app#70]
Internal team notes area for a hack.

Over the course of a hack event there are several types of documentation that needs to be recorded. Currently the team uses a combination of GitHub issues, Dropbox/Google Drive documents and notes to keep track of important historical dates, reasoning for changes, details about scoring methods, and other event specific notes.

A useful feature for the admin team would create a simple blog style notes editor, with dated entries and markdown enabled notes.

Expanding on this feature, it may be important to export the notes after the completion of a hack for reporting and documentation.

**Comment by sbrunswi** [comment]
@charrismatic  did you manage to get this implemented? If so, we could create the markdown and add it!

**Comment by charrismatic** [comment]
I just updated the details here and on the Features Doc

**Comment by ManthanKeim** [comment]
01bb201c27dcc15cc0d760651af5488d26b5a6b4

**Comment by sbrunswi** [comment]
@ManthanKeim  and @charrismatic  I think it would be nice to also have an export feature and the ability to "link" to the notes is something useful to share it with others. I liked those suggestions from Matt but I would put the survey and referencing in the submission as priority now and pick this up once that is done. We should use the notes for the old hacks now and add material.
