### ISSUE TITLE
Data dictionary for platform metrics

### ISSUE THREAD

**Issue by sbrunswi** [ironhacks/ironhacks-app#74]
1) Create a data dictionary  for the stats data in firebase (Platform metrics) to explain each metric and describe what it is measuring 
2) Make the data dictionary accessible via the platform (maybe?) or store it in a central folder

**Comment by charrismatic** [comment]
I think you are looking for the link here: https://ironhacks.github.io/docs/2-Developer-Documentation/metrics/

**Comment by charrismatic** [comment]
Closing as duplicated see #70
