### ISSUE TITLE
Upload screen recording to youtube channel and think about in -app tutorial

### ISSUE THREAD

**Issue by sbrunswi** [ironhacks/ironhacks-app#78]
1) Upload video
2) Produce a tweet about it
3) think about in-app "walk through"

**Comment by ybvau** [comment]
Video: https://youtu.be/GKiAEvg8d9M
(Unfinished) Script: https://docs.google.com/document/d/1amkF0TIW5bNKeXrSBdy5Fc-BoEENmTQjrUtTuWliBgM/edit?usp=sharing

**Comment by sbrunswi** [comment]
@ybvau  did we do that? We have demo's coming up and request for videos about the platform!

**Comment by sbrunswi** [comment]
https://drive.google.com/file/d/1BvHf8HkX6ad03tQI2xFX93ion60I14W7/view here is what @charrismatic has shared. We should add a bitly link and make sure it is easily accessible from our website.

**Comment by ybvau** [comment]
https://bit.ly/30EznGt
https://www.youtube.com/watch?v=8YLLXMhtTB4

I didn't put it on the website - only made it. Let me know if you want me to make any changes
