### ISSUE TITLE
Add testimonials to www.ironhacks.com

### ISSUE THREAD

**Issue by sbrunswi** [ironhacks/ironhacks-app#79]
1) Remove the showcases from the ironhacks.com page
2) Add three testimonials to the page
3) Consider adding video from the screen recording from the past challenge

**Comment by sbrunswi** [comment]
1) Add the two from the www.ironhacks.com/covid19
2) Add the additional quotes from the winners!

**Comment by ERThompson765** [comment]
Dhruvi - (speaking in comparison with competitions in her country [India]) "The takeaway from the hackathon was that I could interact with everyone, but the energy was so healthy and holistic in the way things progressed. We wanted to create a societal impact and not just get to the top. You can literally get inspired by other solutions and then try to implement in your own model." (Regarding what she would share with others in her country) "This is a better way to go about it."


Senthamizhan (winner) - [speaking about insights gained from the competition] "The very important [takeaway] is that we don't have to slap another network on every problem we come across... we in data science should focus more on explainability of machine learning models than going for better and better accuracy... public health officials won't ask us for 90% accuracy, but they will ask how this works... so we should be able to explain to them."

**Comment by ERThompson765** [comment]
![16](https://user-images.githubusercontent.com/64763669/111349147-430af380-8657-11eb-9382-7a10bc3d9884.jpg)
![sendhu_edit](https://user-images.githubusercontent.com/64763669/111349165-456d4d80-8657-11eb-859a-1f91071ca125.jpg)

**Comment by charrismatic** [comment]
Are these photos in the same order as above. 

Dhruvi - Top
Senthamizhan - Bottom
