### ISSUE TITLE
User manager system

### ISSUE THREAD

**Issue by sbrunswi** [ironhacks/ironhacks-app#8]
**Summary**
Add a user management system to manage the registered users and those eligible to participate. Simple querying of the database would be great. 

**Description**
Provide a more detailed write up of your proposal here

**Does this feature solve an existing problem**

**Does this the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context, screenshots, or mockups

**References**
Include any links to existing projects, packages, articles, or issues that would be helpful

**Comment by charrismatic** [comment]
The recent update allows for better viewing of registered users with name, email, date of signup. It also allows you to unregister a user where that is needed.
