### ISSUE TITLE
Set-up a demo hack for first advisory board meeting

### ISSUE THREAD

**Issue by sbrunswi** [ironhacks/ironhacks-app#80]
**Summary**
We need a demo hack that shows the key features of the platform. 

**Description**
Content to be transferred: 
1) Task from COVID-19 data science (Sabine)
2) Tutorials from COVID-19 data science (Matt)
3) Rules (Bryan)
4) Submission: Add two submission examples (copy over from COVID-19)

**Comment by sbrunswi** [comment]
@ManthanKeim and @charrismatic  -  I tried with ironhacks.team@gmail.com but somehow that did not work for me! Can we test this for the meeting on April 21?

**Comment by ManthanKeim** [comment]
Created a demo hack with all the features on Development site, only dummy users to be included and sample submissions and results.

**Comment by ManthanKeim** [comment]
https://dev.ironhacks.com/hacks/demo-hack


With all the features.
