### ISSUE TITLE
Link blog to www.ironhacks.com

### ISSUE THREAD

**Issue by sbrunswi** [ironhacks/ironhacks-app#92]
**Summary**
We need to link the blog with the app. 

**Description**
1. Add blog at the top of the www.ironhacks.com page via the section "upcoming hacks"
2. Add an icon that reflects the upcoming hacks

**Comment by sbrunswi** [comment]
@charrismatic  could you address this soon so that we can send the news release (marketing)

**Comment by charrismatic** [comment]
This was resolved earlier today.
