### ISSUE TITLE
[BUG] Tutorial/Notes event user metrics not getting updated in the firestore database

### ISSUE THREAD

**Issue by ManthanKeim** [ironhacks/ironhacks-app#94]
**Summary**
While creating a new note/tutorial, usermetrics should update the event in the firestore stats collection with the eventide, hackID and the data updated.

**Expected behavior**
User Metrics function should update the firestore with the event and the updated data.

**Comment by charrismatic** [comment]
I checked this on production and staging sites. There doesnt seem to be any issue. 

The event metrics function does not log anything if the environment is not set to 'production'. Most likely this was caused due to using the site on localhost
