### ISSUE TITLE
[BUG] Social tweet not showing up

### ISSUE THREAD

**Issue by sbrunswi** [ironhacks/ironhacks-app#95]
**Summary**
The social feed is currenlty not showing up! Needs to be fixed! Please also give instructions in how to fix it. 

**Description**
Needs to be fixed! Please also give instructions in how to fix it. 
**Steps To Reproduce**
1. log into ironhacks.
2. Check social tweet bar (see screenshot)

**Expected behavior**
Tweet showing up! Bot is not working apparently. 
![Screen Shot 2021-04-20 at 3 22 38 PM](https://user-images.githubusercontent.com/12464227/115452488-7f98b480-a1ec-11eb-82f5-f90902cbbd86.png)

**Screenshots**

**Device Info**
- [ ] Desktop
  - [ ] iOS (version: __ )
  - [ ] Windows (version: __ )
  - [ ] Linux (version: __ )

-  [ ] Mobile 
  - [ ] iPhone (model: __ )
  - [ ] Android (model: __ ) 

**Browser** 
  - [ x] Chrome (version: __ )
  - [ ] Other: ____ 

**Supporting Files**
Include links to logfiles, pastebins, GitHub Gists, etc..

**Comment by ManthanKeim** [comment]
It's working now, must be some issues with the twitter API earlier. If @charrismatic can confirm, we can close this.

**Comment by sbrunswi** [comment]
I think so too but I think we need to restart the bot! I tweeted yesterday (and also the week before) and the #ironhacks is not picked up! @charrismatic..

**Comment by charrismatic** [comment]
I'm not sure what caused this but it looks like twitter made some big updates on the backend.  If you check the twitter list the widget pulls from it was also empty. 

![Screenshot from 2021-04-20 15-45-05](https://user-images.githubusercontent.com/7072452/115608811-bfc36a00-a2b4-11eb-8845-7ff0a9d97354.png)

I don't know what caused this but I was able to fix it by removing everyone from the list then adding them back.
