### ISSUE TITLE
[BUG] Calendar extension not working ! Urgent as we are launching the challenge

### ISSUE THREAD

**Issue by sbrunswi** [ironhacks/ironhacks-app#96]
**Summary**
I added the src= of the google calendar but it is not working. 

**Description**
As shown in the screenshots, the calendar is not shown properly. Not sure why. 
**Steps To Reproduce**
1. Created google calendar. Grabbed the src,
2.  Added it to extension section in the hack, also enabled calendar. 
3. It did not show up proplery. 

**Expected behavior**
the calendar should be visible. 
![Screen Shot 2021-04-25 at 2 03 30 PM](https://user-images.githubusercontent.com/12464227/116004192-9dd92880-a5cf-11eb-9d2a-587a1b031c93.png)

**Screenshots**

**Device Info**
- [ ] Desktop
  - [x ] iOS (version: __ )
  - [ ] Windows (version: __ )
  - [ ] Linux (version: __ )

-  [ ] Mobile 
  - [ ] iPhone (model: __ )
  - [ ] Android (model: __ ) 

**Browser** 
  - [x ] Chrome (version: __ )
  - [ ] Other: ____ 

**Supporting Files**

**Comment by ManthanKeim** [comment]
@sbrunswi Dr. Brunswicker, can you generate link to calendar according to this https://support.google.com/calendar/answer/41207?hl=en and make sure to make it public or give me access to calendar, I'll resolve the issue.

**Comment by ManthanKeim** [comment]
I added a Covid-19-data-science-challenge-spring-2021 Sample calendar as of now for launch.

**Comment by ManthanKeim** [comment]
<img width="1792" alt="Screenshot 2021-04-26 at 12 46 58 AM" src="https://user-images.githubusercontent.com/23071741/116006436-eb35b400-a628-11eb-8b57-5a485378779c.png">

Added the calendar

**Comment by sbrunswi** [comment]
Adding the instructions to the interface so that users understand what to do! 
![Screen Shot 2021-04-29 at 11 59 30 AM](https://user-images.githubusercontent.com/12464227/116581574-77263500-a8e2-11eb-88a6-60a6679458c6.png)

**Comment by ManthanKeim** [comment]
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/23071741/116791135-eca62700-aad5-11eb-8f84-ba3b1f6b0efd.png">
