### ISSUE TITLE
[BUG?] Key generation for new registered users

### ISSUE THREAD

**Issue by sbrunswi** [ironhacks/ironhacks-app#97]
**Summary**
Keys not generated for new registered users! I am not sure if that is done manually. I assume yes! 

**Description**
We opened for registration to test the process of key generation - but there we realized that this process is not automated.  I also do not know where the script is that Matt is running for that. Any help appreciated. 

**Steps To Reproduce**
N/A

**Expected behavior**
Keys available in user profile. 

**Screenshots**

**Device Info**
- [ ] Desktop
  - [ ] iOS (version: __ )
  - [ ] Windows (version: __ )
  - [ ] Linux (version: __ )

-  [ ] Mobile 
  - [ ] iPhone (model: __ )
  - [ ] Android (model: __ ) 

**Browser** 
  - [ ] Chrome (version: __ )
  - [ ] Other: ____ 

**Supporting Files**
N/A

**Comment by ManthanKeim** [comment]
If it's manual, then we have to add key with registered used id to firebase storage with "user_id.json"(https://console.firebase.google.com/u/0/project/ironhacks-c406a/storage/ironhacks-c406a.appspot.com/files~2Fdata~2Fkeys)  and code will fetch accordingly.

**Comment by sbrunswi** [comment]
can you run the script to see if it all works fine?

**Comment by ManthanKeim** [comment]
This all I figured it out with code, unfortunately I don't have any idea about key generation yet and don't know about any script too, sorry.

**Comment by ManthanKeim** [comment]
https://github.com/ironhacks/platform-support-tools/tree/master/bigquery-service-accounts
