### ISSUE TITLE
Question or bug? Cohort specific task material 

### ISSUE THREAD

**Issue by sbrunswi** [ironhacks/ironhacks-app#98]
**Summary**
When specifying the features for the experimental design last year (different treatment groups and different cohorts), we had agreed upon having a distinct task statement for different cohorts! I am trying to set this up but I am not sure if that feature got ever implemented? Also, the goal was to have different submission pages for different cohorts! ...

I am referring to this: https://github.com/ironhacks/ironhacks-app/issues/46 

**Description**
Not sure what got lost here and maybe it is just something that can only be done once the cohorts are assigned?

**Comment by charrismatic** [comment]
Cohorts are able to have separate task documents, they can not have different submissions at this time. 

When creating the task you can set the "default task" in the tasks tab which will be used for any cohorts that do not have a specific task set in the cohorts tab.

![Screenshot from 2021-04-27 12-02-48](https://user-images.githubusercontent.com/7072452/116274645-d9e7c700-a750-11eb-9a44-69ca47571764.png)

To set a cohorts task you can select this from the drop down menu in the cohort settings.

![Screenshot from 2021-04-27 12-03-00](https://user-images.githubusercontent.com/7072452/116274656-dc4a2100-a750-11eb-8cce-7e7bcb4d0d23.png)

**Comment by sbrunswi** [comment]
ok - I remember that we also discussed having separate submission markdowns but I think we said we do it at a later stage because we did not need it for that particular challenge in fall! I am good with this, and will ask people to test it before release the task!
