### ISSUE TITLE
[BUG] USERS THAT ARE FILLING IN REGISTRATION SURVEY DO NOT SHOW UP AS registered users

### ISSUE THREAD

**Issue by sbrunswi** [ironhacks/ironhacks-app#99]
**Summary**
Registration with qualtrics integration is not working; there is a bug. This is a MAJOR issue to move forward with the challenge. 

**Description**
Today, I logged into qualtrics and saw that at least 10 users have submitted/completed the survey but are not registered in the challenge.  There seems to be an issue with the registration process! 

**Steps To Reproduce**
1. Check qualtrics data 
2. Check registered users on firebase for the challenge 
3.  There is a mismatch: on firebase we have only the admins but the people who filled in the registration survey are not registered. 

**Expected behavior**
I assume that those that fill in the registration survey are also on the platform. 

**Supporting Files**
[IronHacks+COVID-19+Challenge+SS-2021+Registration+Survey_May+4,+2021_13.14.zip](https://github.com/ironhacks/ironhacks-app/files/6423326/IronHacks%2BCOVID-19%2BChallenge%2BSS-2021%2BRegistration%2BSurvey_May%2B4.%2B2021_13.14.zip)

**Comment by ManthanKeim** [comment]
Solved by @charrismatic , was issue with some firebase rules.
